---
version: 0.1

phases:
  install:
    commands:
      - npm install yarn@0.19.1 -g
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - yarn install
      - mkdir -p ./dist/node_modules
      - cp ./src/index.js ./dist/
      - cp -r ./node_modules/moment ./dist/node_modules/moment
      - cp -r ./node_modules/moment-timezone ./dist/node_modules/moment-timezone
artifacts:
  type: zip
  files:
    - "./dist/*"
  discard-paths: no