---
version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - npm install yarn -g
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - yarn install
      - mkdir dist 
      - zip -r dist/package.zip index.js node_modules/moment node_modules/moment-timezone
artifacts:
  files:
    - "./dist/*"
  discard-paths: no